### ISSUE TITLE
Appveyor builds don't work using appveyor.yml

### ISSUE THREAD

**Issue by speth** [Cantera/conda-recipes#3]
I had previously gotten Appveyor working by configuring it using their web interface. This interface provides the supposedly equivalent YML file, but trying to add an `appveyor.yml` file that combines what was done for the x86 and x64 builds doesn't seem to work. The previously-working (pre conda-build 2.0) configs were, for x64:
```yml
version: 1.0.{build}
environment:
  ANACONDA_KEY:
    secure: 3ZFhc2nXAfGp3E1OJ6jnXHmjWcEPwRJcpanlvQAJMigQQ7oi/Q4OOM07ip3Nv8lz
install:
- cmd: >-
    set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%

    conda install -y anaconda-client conda-build
build_script:
- cmd: conda build cantera --python=2.7 --python=3.4 --python=3.5 --numpy=1.11
deploy_script:
- cmd: anaconda -t %ANACONDA_KEY% upload --force -l dev C:\Miniconda\conda-bld\win-32\cantera*.tar.bz2
```
and for x86:
```yml
version: 1.0.{build}
environment:
  ANACONDA_KEY:
    secure: 3ZFhc2nXAfGp3E1OJ6jnXHmjWcEPwRJcpanlvQAJMigQQ7oi/Q4OOM07ip3Nv8lz
install:
- cmd: >-
    set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%PATH%

    conda install -y anaconda-client conda-build
build_script:
- cmd: >-
    set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%PATH%

    conda build cantera --python=2.7 --python=3.4 --python=3.5 --numpy=1.11
deploy_script:
- cmd: anaconda -t %ANACONDA_KEY% upload --force -l dev C:\Miniconda-x64\conda-bld\win-64\cantera*.tar.bz2
```
The build gets as far as creating the `cantera-builder` environment, but then fails with the error:
```
'scons' is not recognized as an internal or external command, operable program or batch file
```
For the last successful build (https://ci.appveyor.com/project/speth/conda-recipes/build/1.0.13), from the same point (after the message about how to activate/deactivate the new environment), it used to say:
```
Using Anaconda API: https://api.anaconda.org
scons: Reading SConscript files ...
```
